CREATE TABLE EVENT (
    id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(800),
    location VARCHAR(500)
);

CREATE TABLE USERS (
    id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    password VARCHAR(50),
    email VARCHAR(50)
);

